// This file was generated by a tool. Only edit for local testing purposes.
// TASK: TRO WI17211 - Add documentation for enumerations and their values when available.
#pragma warning disable 1591 // Disable warnings related to xml documentation

namespace TDOC.Data.Enumerations
{
    /// <summary>
    /// Values:
    /// <para>
    /// Off = 0, WarningPrompt = 1, Error = 2
    /// </para>
    /// </summary>
    public enum ActualProgramCheck
    {
        Off = 0,
        WarningPrompt = 1,
        Error = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Lite = 0, Label = 1, Cycle = 2, CyclePro = 3, Admin = 4
    /// </para>
    /// </summary>
    public enum AdminType
    {
        Lite = 0,
        Label = 1,
        Cycle = 2,
        CyclePro = 3,
        Admin = 4
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Old = 0, New = 1, Deleted = 2, Edited = 3
    /// </para>
    /// </summary>
    public enum AlternativeArticleStatus
    {
        Old = 0,
        New = 1,
        Deleted = 2,
        Edited = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// No = 0, Yes = 1, Visual = 2, Unit = 3, UnitVisual = 4
    /// </para>
    /// </summary>
    public enum ApprovalType
    {
        No = 0,
        Yes = 1,
        Visual = 2,
        Unit = 3,
        UnitVisual = 4
    };

    /// <summary>
    /// Values:
    /// <para>
    /// OK = 0, BatchFailed = 1, UnitFailed = 2
    /// </para>
    /// </summary>
    public enum BatchUnitStatus
    {
        OK = 0,
        BatchFailed = 1,
        UnitFailed = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Daily = 0, DailyPerMachine = 1, None = 2
    /// </para>
    /// </summary>
    public enum CBIUsageMode
    {
        Daily = 0,
        DailyPerMachine = 1,
        None = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Name = 0, ShortName = 1, Number = 2
    /// </para>
    /// </summary>
    public enum CustNameDisplay
    {
        Name = 0,
        ShortName = 1,
        Number = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Default = 0, Disabled = 1, Manual = 2, Automation = 3
    /// </para>
    /// </summary>
    public enum CustOrderBookingMode
    {
        Default = 0,
        Disabled = 1,
        Manual = 2,
        Automation = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// UseFacSetting = 0, Always = 1, Never = 2
    /// </para>
    /// </summary>
    public enum CustPreDispatchMode
    {
        UseFacSetting = 0,
        Always = 1,
        Never = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Off = 0, Prompt = 1, On = 2
    /// </para>
    /// </summary>
    public enum DecNonDispItemStockOnPack
    {
        Off = 0,
        Prompt = 1,
        On = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Delta = 0, Total = 1
    /// </para>
    /// </summary>
    public enum DeltaScanMode
    {
        Delta = 0,
        Total = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NotSet = 0, Needed = 1, Required = 2
    /// </para>
    /// </summary>
    public enum DoctorUsage
    {
        NotSet = 0,
        Needed = 1,
        Required = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, None = 1
    /// </para>
    /// </summary>
    public enum ExpireType
    {
        Normal = 0,
        None = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// On = 0, Off = 1
    /// </para>
    /// </summary>
    public enum FacDeductItemsFromStockInOpType
    {
        On = 0,
        Off = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Disabled = 0, Manual = 1, Automation = 2
    /// </para>
    /// </summary>
    public enum FacOrderBookingMode
    {
        Disabled = 0,
        Manual = 1,
        Automation = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Off = 0, Auto = 1
    /// </para>
    /// </summary>
    public enum FactoryCustOrderAcceptMode
    {
        Off = 0,
        Auto = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// ProductSerial = 0, Product = 1
    /// </para>
    /// </summary>
    public enum FactoryDefProdTraceType
    {
        ProductSerial = 0,
        Product = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Default = 0, On = 1, Warning = 2, Off = 3
    /// </para>
    /// </summary>
    public enum FactoryRestrictionMode
    {
        Default = 0,
        On = 1,
        Warning = 2,
        Off = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// General = 0, AdHoc = 1, TemplateOnly = 2
    /// </para>
    /// </summary>
    public enum FastTrackCodeType
    {
        General = 0,
        AdHoc = 1,
        TemplateOnly = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// System = 0, JobServer = 1, FacUser = 2, CustUser = 3
    /// </para>
    /// </summary>
    public enum FastTrackCreatorType
    {
        System = 0,
        JobServer = 1,
        FacUser = 2,
        CustUser = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// UserSetting = 0, ForcePrompt = 1, ForceNoPrompt = 2, ForceNoPromptOrInfo = 3
    /// </para>
    /// </summary>
    public enum FastTrackDisplayMode
    {
        UserSetting = 0,
        ForcePrompt = 1,
        ForceNoPrompt = 2,
        ForceNoPromptOrInfo = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, NormalNewUnitHas = 1, ToRepair = 2, Expired = 3, Cancelled = 4
    /// </para>
    /// </summary>
    public enum FastTrackEndType
    {
        Normal = 0,
        NormalNewUnitHas = 1,
        ToRepair = 2,
        Expired = 3,
        Cancelled = 4
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Factory = 1, Customer = 2
    /// </para>
    /// </summary>
    public enum FastTrackInvoiceType
    {
        None = 0,
        Factory = 1,
        Customer = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Assigned = 0, Started = 1, Ended = 2
    /// </para>
    /// </summary>
    public enum FastTrackStatus
    {
        Assigned = 0,
        Started = 1,
        Ended = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Disabled = 0, Enabled = 1
    /// </para>
    /// </summary>
    public enum FastTrackStockBasedMode
    {
        Disabled = 0,
        Enabled = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// AllWithDate = 0, Operation = 1
    /// </para>
    /// </summary>
    public enum FastTrackStockBasedOrdersFilter
    {
        AllWithDate = 0,
        Operation = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Enabled = 0, Disabled = 1
    /// </para>
    /// </summary>
    public enum IdentArticleLineUsage
    {
        Enabled = 0,
        Disabled = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Off = 0, Prompt = 1, On = 2
    /// </para>
    /// </summary>
    public enum IncNonDispItemStockOnPack
    {
        Off = 0,
        Prompt = 1,
        On = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Other = 0, Batch = 1
    /// </para>
    /// </summary>
    public enum IncubatorType
    {
        Other = 0,
        Batch = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Created = 0, InBatch = 1, Pending = 2, Approved = 3, Disapproved = 4,
    /// Cancelled = 5
    /// </para>
    /// </summary>
    public enum IndicStatus
    {
        Created = 0,
        InBatch = 1,
        Pending = 2,
        Approved = 3,
        Disapproved = 4,
        Cancelled = 5
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Units = 1, Orders = 2, EndoDryers = 3, EndoListUse = 4,
    /// EndoListClean = 5, NeedsList = 6, Incubators = 7, IndicatorQueue = 8, ProdOverview = 9,
    /// EndoProdOverview = 10, ItemExchange = 11, Distribution = 12, ScheduledOperation = 13, ReturnRequested = 14
    /// </para>
    /// </summary>
    public enum InfoOverviewType
    {
        None = 0,
        Units = 1,
        Orders = 2,
        EndoDryers = 3,
        EndoListUse = 4,
        EndoListClean = 5,
        NeedsList = 6,
        Incubators = 7,
        IndicatorQueue = 8,
        ProdOverview = 9,
        EndoProdOverview = 10,
        ItemExchange = 11,
        Distribution = 12,
        ScheduledOperation = 13,
        ReturnRequested = 14
    }; // InfoOverviewType

    /// <summary>
    /// Values:
    /// <para>
    /// Immediate = 0, Delayed = 1, Combined = 2
    /// </para>
    /// </summary>
    public enum InTypResultType
    {
        Immediate = 0,
        Delayed = 1,
        Combined = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, SalesPrice = 1, UsagePrice = 2, CostPrice = 3
    /// </para>
    /// </summary>
    public enum ItemAltPricingMode
    {
        None = 0,
        SalesPrice = 1,
        UsagePrice = 2,
        CostPrice = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Default = 0, Fixed = 1, Sum = 2, Max = 3, Count = 4
    /// </para>
    /// </summary>
    public enum ItemDifficultyMode
    {
        Default = 0,
        Fixed = 1,
        Sum = 2,
        Max = 3,
        Count = 4
    };

    /// <summary>
    /// Values:
    /// <para>
    /// SalesPrice = 0, UsagePrice = 1, CostPrice = 2
    /// </para>
    /// </summary>
    public enum ItemPricingMode
    {
        SalesPrice = 0,
        UsagePrice = 1,
        CostPrice = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, TimeBased = 1
    /// </para>
    /// </summary>
    public enum ItemPricingType
    {
        Normal = 0,
        TimeBased = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NotRequired = 0, Enabled = 1
    /// </para>
    /// </summary>
    public enum ItemReservationMode
    {
        NotRequired = 0,
        Enabled = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Blocked = 1
    /// </para>
    /// </summary>
    public enum ItemSalesRestriction
    {
        None = 0,
        Blocked = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Item = 0, SerialItem = 1, LOT = 2
    /// </para>
    /// </summary>
    public enum ItemTraceType
    {
        Item = 0,
        SerialItem = 1,
        LOT = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Admin = 1, Machine = 2
    /// </para>
    /// </summary>
    public enum LocaSubProcessType
    {
        None = 0,
        Admin = 1,
        Machine = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Disabled = 0, Enabled = 1
    /// </para>
    /// </summary>
    public enum LogBatchContent
    {
        Disabled = 0,
        Enabled = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Off = 0, On = 1
    /// </para>
    /// </summary>
    public enum LogBatchRegMode
    {
        Off = 0,
        On = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NotAllowed = 0, UserName = 1, UserNamePassword = 2, Autologin = 3
    /// </para>
    /// </summary>
    public enum LoginCookieMethod
    {
        NotAllowed = 0,
        UserName = 1,
        UserNamePassword = 2,
        Autologin = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Active = 0, Disabled = 1
    /// </para>
    /// </summary>
    public enum LotStatus
    {
        Active = 0,
        Disabled = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// UseModelValue = 0, Yes = 1, No = 2
    /// </para>
    /// </summary>
    public enum MachineLoadOnStart
    {
        UseModelValue = 0,
        Yes = 1,
        No = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Visible = 0, Hidden = 1
    /// </para>
    /// </summary>
    public enum MachineVisiblity
    {
        Visible = 0,
        Hidden = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Off = 0, On = 1, Required = 2
    /// </para>
    /// </summary>
    public enum MachPlacementUsageMode
    {
        Off = 0,
        On = 1,
        Required = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NotAllowed = 0, Allowed = 1, Assumed = 2
    /// </para>
    /// </summary>
    public enum ManualEndoDryingMode
    {
        NotAllowed = 0,
        Allowed = 1,
        Assumed = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Actual = 0, Work = 1
    /// </para>
    /// </summary>
    public enum MinOrderLeadTime
    {
        Actual = 0,
        Work = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Created = 0, Cancelled = 1, Planned = 2, Accepted = 3, Started = 4,
    /// Done = 5, PrefListToOrderAuto = 6, PrefListToOrderManual = 7, PrefListOrderUpdated = 8, OrderCancelled = 9,
    /// Exported = 10, Imported = 11, PickInfoImport = 12, BookingForced = 13, BookingUnForced = 14,
    /// ReservChangedDueToForce = 15, PreCount = 16, PerCount = 17, PostCount = 18, MergeRemove = 19,
    /// MergeReceive = 20, EmergencyCaseCartAdded = 21, PatVeriOK = 22, PatVeriFailed = 23, PatVeriSkip = 24,
    /// PatVeriPostpone = 25, OrderReturnRequested = 26, OrderReordered = 27, OrderCopyCreatedAuto = 28, OrderCopyCreatedManual = 29
    /// </para>
    /// </summary>
    public enum OperationDataActionType
    {
        Created = 0,
        Cancelled = 1,
        Planned = 2,
        Accepted = 3,
        Started = 4,
        Done = 5,
        PrefListToOrderAuto = 6,
        PrefListToOrderManual = 7,
        PrefListOrderUpdated = 8,
        OrderCancelled = 9,
        Exported = 10,
        Imported = 11,
        PickInfoImport = 12,
        BookingForced = 13,
        BookingUnForced = 14,
        ReservChangedDueToForce = 15,
        PreCount = 16,
        PerCount = 17,
        PostCount = 18,
        MergeRemove = 19,
        MergeReceive = 20,
        EmergencyCaseCartAdded = 21,
        PatVeriOK = 22,
        PatVeriFailed = 23,
        PatVeriSkip = 24,
        PatVeriPostpone = 25,
        OrderReturnRequested = 26,
        OrderReordered = 27,
        OrderCopyCreatedAuto = 28,
        OrderCopyCreatedManual = 29
    }; // OperationDataActionType

    /// <summary>
    /// Values:
    /// <para>
    /// Elective = 0, Emergency = 1
    /// </para>
    /// </summary>
    public enum OperationTypeType
    {
        Elective = 0,
        Emergency = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Undetermined = 0, Disabled = 1, Inactive = 2, Active = 3
    /// </para>
    /// </summary>
    public enum OrderBookingMode
    {
        Undetermined = 0,
        Disabled = 1,
        Inactive = 2,
        Active = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, High = 1, Force = 2
    /// </para>
    /// </summary>
    public enum OrderBookingPriority
    {
        Normal = 0,
        High = 1,
        Force = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Undetermined = 0, Ok = 1, Warning = 2, Error = 3
    /// </para>
    /// </summary>
    public enum OrderBookingStatus
    {
        Undetermined = 0,
        Ok = 1,
        Warning = 2,
        Error = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Unlocked = 0, Locked = 1
    /// </para>
    /// </summary>
    public enum OrderLockMode
    {
        Unlocked = 0,
        Locked = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NA = 0, Synced = 1, Stopped = 2
    /// </para>
    /// </summary>
    public enum OrderOperationSyncMode
    {
        NA = 0,
        Synced = 1,
        Stopped = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Template = 1, Open = 2, Sent = 3, Received = 4,
    /// Done = 5, Cancelled = 6
    /// </para>
    /// </summary>
    public enum OrderOrgStatus
    {
        None = 0,
        Template = 1,
        Open = 2,
        Sent = 3,
        Received = 4,
        Done = 5,
        Cancelled = 6
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, FullAuto = 1, EjectOnly = 2
    /// </para>
    /// </summary>
    public enum OrderSuppPickMode
    {
        Normal = 0,
        FullAuto = 1,
        EjectOnly = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, PickNow = 1, PickNowForced = 2
    /// </para>
    /// </summary>
    public enum OrderSuppPickPriority
    {
        Normal = 0,
        PickNow = 1,
        PickNowForced = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, FastTrack = 1, Emergency = 2
    /// </para>
    /// </summary>
    public enum OrderSuppPriority
    {
        Normal = 0,
        FastTrack = 1,
        Emergency = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Template = 1, Order = 2, Accepted = 3, Picked = 4,
    /// Delivered = 5, Cancelled = 6
    /// </para>
    /// </summary>
    public enum OrderSuppStatus
    {
        None = 0,
        Template = 1,
        Order = 2,
        Accepted = 3,
        Picked = 4,
        Delivered = 5,
        Cancelled = 6
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Order = 1, ReturnOrder = 2, OrderCorr = 3
    /// </para>
    /// </summary>
    public enum OrderType
    {
        None = 0,
        Order = 1,
        ReturnOrder = 2,
        OrderCorr = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// All = 0, Endoscopes = 1
    /// </para>
    /// </summary>
    public enum PackingUsedFor
    {
        All = 0,
        Endoscopes = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, TDOC = 1, ActiveDirectory = 2
    /// </para>
    /// </summary>
    public enum PasswordVerificationMethod
    {
        None = 0,
        TDOC = 1,
        ActiveDirectory = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NotSet = 0, Needed = 1, Required = 2
    /// </para>
    /// </summary>
    public enum PatientAgeUsage
    {
        NotSet = 0,
        Needed = 1,
        Required = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NotSet = 0, Needed = 1, Required = 2
    /// </para>
    /// </summary>
    public enum PatientGenderUsage
    {
        NotSet = 0,
        Needed = 1,
        Required = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, SystemData = 1, User = 2, UserProfile = 3, PatientLookup = 4,
    /// OperationLookup = 5, Patients = 6, Operations = 7, Units = 8, Orders = 9,
    /// LOTLookup = 10
    /// </para>
    /// </summary>
    public enum PIPLogEntrySubType
    {
        None = 0,
        SystemData = 1,
        User = 2,
        UserProfile = 3,
        PatientLookup = 4,
        OperationLookup = 5,
        Patients = 6,
        Operations = 7,
        Units = 8,
        Orders = 9,
        LOTLookup = 10
    }; // PIPLogEntrySubType

    /// <summary>
    /// Values:
    /// <para>
    /// PIPSettings = 0, DirectLookup = 1, SuccSearch = 2, UnSuccSearch = 3, PIPLogOpened = 4,
    /// PIPLogSearching = 5, SchedOperations = 6
    /// </para>
    /// </summary>
    public enum PIPLogEntryType
    {
        PIPSettings = 0,
        DirectLookup = 1,
        SuccSearch = 2,
        UnSuccSearch = 3,
        PIPLogOpened = 4,
        PIPLogSearching = 5,
        SchedOperations = 6
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Immediate = 0, TimeBased = 1, Manual = 2
    /// </para>
    /// </summary>
    public enum PrefListOrderCreateMode
    {
        Immediate = 0,
        TimeBased = 1,
        Manual = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Done = 0, Running = 1, Initiated = 2, Ending = 3
    /// </para>
    /// </summary>
    public enum ProcessStatus
    {
        Done = 0,
        Running = 1,
        Initiated = 2,
        Ending = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Pack = 1, SteriPostBatch = 2, Out = 3, Return = 4,
    /// Prepare = 5, Wrap = 6, LitePro = 7, SteriPreBatch = 8, Flash = 9,
    /// Location = 10, WashPreBatch = 11, WashPostBatch = 12, OpenUsed = 13, Operation = 14,
    /// Order = 15, Inventory = 16, OrderPick = 17, Industry = 18, PreDisPreBatch = 19,
    /// LoadQueue = 20, PurchaseOrder = 21, EndoscopePreBatch = 22, WashCheck = 23, ExtBatchInfo = 24,
    /// EndoCleanAndTest = 25, Transport = 26, Workflow = 27, Incubator = 28, ReturnWF = 29,
    /// WashPreBatchWF = 30, SteriPreBatchWF = 31, PackWF = 32, OutWF = 33, WashPostBatchWF = 34,
    /// SteriPostBatchWF = 35, Last = 36
    /// </para>
    /// </summary>
    public enum ProcessType
    {
        None = 0,
        Pack = 1,
        SteriPostBatch = 2,
        Out = 3,
        Return = 4,
        Prepare = 5,
        Wrap = 6,
        LitePro = 7,
        SteriPreBatch = 8,
        Flash = 9,
        Location = 10,
        WashPreBatch = 11,
        WashPostBatch = 12,
        OpenUsed = 13,
        Operation = 14,
        Order = 15,
        Inventory = 16,
        OrderPick = 17,
        Industry = 18,
        PreDisPreBatch = 19,
        LoadQueue = 20,
        PurchaseOrder = 21,
        EndoscopePreBatch = 22,
        WashCheck = 23,
        ExtBatchInfo = 24,
        EndoCleanAndTest = 25,
        Transport = 26,
        Workflow = 27,
        Incubator = 28,
        ReturnWF = 29,
        WashPreBatchWF = 30,
        SteriPreBatchWF = 31,
        PackWF = 32,
        OutWF = 33,
        WashPostBatchWF = 34,
        SteriPostBatchWF = 35,
        Last = 36
    }; // ProcessType

    /// <summary>
    /// Values:
    /// <para>
    /// Default = 0, None = 1, CustomerOrSite = 2, CustomerElseSite = 3, CustomerOnly = 4
    /// </para>
    /// </summary>
    public enum ProdDispatchRestriction
    {
        Default = 0,
        None = 1,
        CustomerOrSite = 2,
        CustomerElseSite = 3,
        CustomerOnly = 4
    };

    /// <summary>
    /// Values:
    /// <para>
    /// AsDefinedForUsers = 0, Always = 1, Never = 2
    /// </para>
    /// </summary>
    public enum ProdOverviewAvailability
    {
        AsDefinedForUsers = 0,
        Always = 1,
        Never = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, AvailableInWeb = 1, NotAvailableInWeb = 2
    /// </para>
    /// </summary>
    public enum ProdOverviewVisibilityMode
    {
        None = 0,
        AvailableInWeb = 1,
        NotAvailableInWeb = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NotRequired = 0, Enabled = 1
    /// </para>
    /// </summary>
    public enum ProdReservationMode
    {
        NotRequired = 0,
        Enabled = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// UseItemValue = 0, Fixed = 1
    /// </para>
    /// </summary>
    public enum ProductDifficultyMode
    {
        UseItemValue = 0,
        Fixed = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Cycle = 0, CSM = 1, CSMLabel = 2, SDM = 3, TDOC2000 = 4,
    /// EndoCycle = 5, EndoTrace = 6, Standalone = 7, Select = 8
    /// </para>
    /// </summary>
    public enum ProductLine
    {
        Cycle = 0,
        CSM = 1,
        CSMLabel = 2,
        SDM = 3,
        TDOC2000 = 4,
        EndoCycle = 5,
        EndoTrace = 6,
        Standalone = 7,
        Select = 8
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NonLoaner = 0, GenericLoaner = 1, ExternalLoaner = 2, LoanerTemplate = 3
    /// </para>
    /// </summary>
    public enum ProductLoanerType
    {
        NonLoaner = 0,
        GenericLoaner = 1,
        ExternalLoaner = 2,
        LoanerTemplate = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, NotOrdered = 1, PickedFromLineSpec = 2
    /// </para>
    /// </summary>
    public enum ProductReservationType
    {
        Normal = 0,
        NotOrdered = 1,
        PickedFromLineSpec = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Normal = 0, PreProcessed = 1, PrePacked = 2
    /// </para>
    /// </summary>
    public enum ProductReturnState
    {
        Normal = 0,
        PreProcessed = 1,
        PrePacked = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Simple = 0, Basic = 1, Advanced = 2
    /// </para>
    /// </summary>
    public enum ProductStockControlMode
    {
        Simple = 0,
        Basic = 1,
        Advanced = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Factory = 0, Transit = 1
    /// </para>
    /// </summary>
    public enum ProductStorageType
    {
        Factory = 0,
        Transit = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Product = 0, ProductSerial = 1, Both = 2
    /// </para>
    /// </summary>
    public enum ProductTraceType
    {
        Product = 0,
        ProductSerial = 1,
        Both = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Trays = 0, SinglePacks = 1, Endoscopes = 2
    /// </para>
    /// </summary>
    public enum ProductType
    {
        Trays = 0,
        SinglePacks = 1,
        Endoscopes = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Allowed = 0, Required = 1
    /// </para>
    /// </summary>
    public enum ProgramCheckInitiated
    {
        Allowed = 0,
        Required = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// AskUser = 0, UsingCust = 1, Owner = 2, Factory = 3
    /// </para>
    /// </summary>
    public enum RepairMode
    {
        AskUser = 0,
        UsingCust = 1,
        Owner = 2,
        Factory = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Undetermined = 0, OKOriginal = 1, OKIdentical = 2, OKAlternative = 3, OKIdenticalForAlternative = 4,
    /// WarningOriginal = 5, WarningIdentical = 6, WarningAlternative = 7, WarningIdenticalForAlternative = 8, Error = 9
    /// </para>
    /// </summary>
    public enum ReservationState
    {
        Undetermined = 0,
        OKOriginal = 1,
        OKIdentical = 2,
        OKAlternative = 3,
        OKIdenticalForAlternative = 4,
        WarningOriginal = 5,
        WarningIdentical = 6,
        WarningAlternative = 7,
        WarningIdenticalForAlternative = 8,
        Error = 9
    }; // ReservationState

    /// <summary>
    /// Values:
    /// <para>
    /// Default = 0, Layers = 1, Grid = 2
    /// </para>
    /// </summary>
    public enum ScanUIStartMode
    {
        Default = 0,
        Layers = 1,
        Grid = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Order = 0, PurchaseOrder = 1, ReturnOrder = 2, ReturnRequest = 3, OrderCorrection = 4,
    /// Operation = 5, PickJobForecast = 6, PickJobList = 7
    /// </para>
    /// </summary>
    public enum SequenceType
    {
        Order = 0,
        PurchaseOrder = 1,
        ReturnOrder = 2,
        ReturnRequest = 3,
        OrderCorrection = 4,
        Operation = 5,
        PickJobForecast = 6,
        PickJobList = 7
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Item = 0, Packing = 1
    /// </para>
    /// </summary>
    public enum SerialType
    {
        Item = 0,
        Packing = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Male = 1, Female = 2, Other = 3
    /// </para>
    /// </summary>
    public enum SexType
    {
        None = 0,
        Male = 1,
        Female = 2,
        Other = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// NotAllowed = 0, Allowed = 1, Required = 2
    /// </para>
    /// </summary>
    public enum StdCommentFreeTextOption
    {
        NotAllowed = 0,
        Allowed = 1,
        Required = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// No = 0, Yes = 1
    /// </para>
    /// </summary>
    public enum StdCommentShowInProdOption
    {
        No = 0,
        Yes = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Never = 0, Always = 1, Ask = 2, WhenSet = 3, WhenSetAuto = 4
    /// </para>
    /// </summary>
    public enum StockBackOrderMode
    {
        Never = 0,
        Always = 1,
        Ask = 2,
        WhenSet = 3,
        WhenSetAuto = 4
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Auto = 0, Receive = 1, Manual = 2
    /// </para>
    /// </summary>
    public enum StockOrderInMode
    {
        Auto = 0,
        Receive = 1,
        Manual = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Never = 0, Always = 1, Ask = 2
    /// </para>
    /// </summary>
    public enum StockPrnMode
    {
        Never = 0,
        Always = 1,
        Ask = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Item = 0, Product = 1
    /// </para>
    /// </summary>
    public enum SubstitutionArticleType
    {
        Item = 0,
        Product = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Identical = 1, Alternative = 2, IdenticalForAlternative = 3
    /// </para>
    /// </summary>
    public enum SubstitutionReason
    {
        None = 0,
        Identical = 1,
        Alternative = 2,
        IdenticalForAlternative = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Identical = 0, Alternative = 1
    /// </para>
    /// </summary>
    public enum SubstMode
    {
        Identical = 0,
        Alternative = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Product = 1, Serial = 2, Item = 3, Machine = 4,
    /// Supplier = 5, Customer = 6, System = 7, Unit = 8, Text = 9,
    /// Factory = 10, Lot_OBSOLETE = 11, Stocks = 12, User = 13, Process = 14,
    /// LotTransAct_OBSOLETE = 15, Location = 16, RushPlan = 17, OperationData = 18, OperationType = 19,
    /// ProcedureType = 20, Program = 21, ProgramRecipe = 22, Catalog = 23, Patient = 24,
    /// Order = 25, MachineType = 26, ProgramGroup = 27, RepairType = 28, Repair = 29,
    /// Doctor = 30, IndicatorType = 31, Room = 32, Pack = 33, FastTrackCode = 34,
    /// FastTrackPlan = 35, FastTrackGroup = 36, WashCheckType = 37, InfoOverviewConfig = 38, Indicator = 39,
    /// TransportMethod = 40, HandlingStep = 41, LocationGroup = 42, CustSite = 43, Tags = 44,
    /// DryerProcess = 45, StandardComment = 46, AGS = 47, TagType = 48, Trigger = 49,
    /// ScannerMacro = 50
    /// </para>
    /// </summary>
    public enum TableTypes
    {
        None = 0,
        Product = 1,
        Serial = 2,
        Item = 3,
        Machine = 4,
        Supplier = 5,
        Customer = 6,
        System = 7,
        Unit = 8,
        Text = 9,
        Factory = 10,
        Lot_OBSOLETE = 11,
        Stocks = 12,
        User = 13,
        Process = 14,
        LotTransAct_OBSOLETE = 15,
        Location = 16,
        RushPlan = 17,
        OperationData = 18,
        OperationType = 19,
        ProcedureType = 20,
        Program = 21,
        ProgramRecipe = 22,
        Catalog = 23,
        Patient = 24,
        Order = 25,
        MachineType = 26,
        ProgramGroup = 27,
        RepairType = 28,
        Repair = 29,
        Doctor = 30,
        IndicatorType = 31,
        Room = 32,
        Pack = 33,
        FastTrackCode = 34,
        FastTrackPlan = 35,
        FastTrackGroup = 36,
        WashCheckType = 37,
        InfoOverviewConfig = 38,
        Indicator = 39,
        TransportMethod = 40,
        HandlingStep = 41,
        LocationGroup = 42,
        CustSite = 43,
        Tags = 44,
        DryerProcess = 45,
        StandardComment = 46,
        AGS = 47,
        TagType = 48,
        Trigger = 49,
        ScannerMacro = 50
    }; // TableTypes

    /// <summary>
    /// Values:
    /// <para>
    /// Basket = 0, SteriLoad = 1, PrepTag = 2, Bundle = 3, Wash = 4,
    /// WashLoad = 5, Transport = 6, Split = 7, CaseCart = 8, TransportBox = 9,
    /// InstrumentContainer = 10
    /// </para>
    /// </summary>
    public enum TagType
    {
        Basket = 0,
        SteriLoad = 1,
        PrepTag = 2,
        Bundle = 3,
        Wash = 4,
        WashLoad = 5,
        Transport = 6,
        Split = 7,
        CaseCart = 8,
        TransportBox = 9,
        InstrumentContainer = 10
    }; // TagType

    /// <summary>
    /// Values:
    /// <para>
    /// Unknown = 0, AppServer = 1, ScannerServer = 2, ConnectServer = 3, TDOCCtrl = 4,
    /// Admin = 5, Scanner = 6, Connect = 7, Spool_Obsolete = 8, Launcher = 9,
    /// Exchange = 10, MacView = 11, Service = 12, PrintServer = 13, RemoteControl_Obsolete = 14,
    /// JobServer_Obsolete = 15, ProfEdit = 16, DeviceTest = 17, MacSimu = 18, IniEdit = 19,
    /// NetTest = 20, UtilityServer = 21, SpoolServer = 22, SpoolCtrl = 23, NetCOMCfg = 24,
    /// JobCfg = 25, Panel = 26, JobServer = 27, WebServer = 28, Engine = 29,
    /// Upgrade = 30, UnknownL = 31
    /// </para>
    /// </summary>
    public enum TDOCAppType
    {
        Unknown = 0,
        AppServer = 1,
        ScannerServer = 2,
        ConnectServer = 3,
        TDOCCtrl = 4,
        Admin = 5,
        Scanner = 6,
        Connect = 7,
        Spool_Obsolete = 8,
        Launcher = 9,
        Exchange = 10,
        MacView = 11,
        Service = 12,
        PrintServer = 13,
        RemoteControl_Obsolete = 14,
        JobServer_Obsolete = 15,
        ProfEdit = 16,
        DeviceTest = 17,
        MacSimu = 18,
        IniEdit = 19,
        NetTest = 20,
        UtilityServer = 21,
        SpoolServer = 22,
        SpoolCtrl = 23,
        NetCOMCfg = 24,
        JobCfg = 25,
        Panel = 26,
        JobServer = 27,
        WebServer = 28,
        Engine = 29,
        Upgrade = 30,
        UnknownL = 31
    }; // TDOCAppType

    /// <summary>
    /// Values:
    /// <para>
    /// None = 0, Text = 1, Pack = 2, PictureRef = 3, Program = 4,
    /// User = 5, MachineType = 6, Machine = 7, Cust = 8, Item = 9,
    /// Product = 10, System = 11, Composite = 12, Stock = 13, Process = 14,
    /// Unit = 15, Event = 16, Serial = 17, Trigger = 18, Supplier = 19,
    /// CustTransAct = 20, Pics = 21, BcTp = 22, Contact = 23, Profile = 24,
    /// ItemGrp = 25, Delta = 26, Position = 27, Patient = 28, PatientCons = 29,
    /// UnitLocation = 30, UnitList = 31, Repair = 32, RepairType = 33, Stocks = 34,
    /// Factory = 35, Location = 36, ProgGroups = 37, ProgGroup = 38, Report = 39,
    /// ReportDef = 40, RepSelection = 41, ItemSerialUsage = 42, Order = 43, OrderLine = 44,
    /// OrderLineSpec = 45, PosLocation = 46, PrnDrv = 47, Audit = 48, Defaults = 49,
    /// History = 50, TriggerLog = 51, OperationType = 52, ProcedureType = 53, ProcedureTypes = 54,
    /// ProcedureData = 55, OperationData = 56, Doctor = 57, OrderSuggestion = 58, OrderLineSugg = 59,
    /// OrderTemplate = 60, OrderLineTemp = 61, DefaultsBlob = 62, Batch = 63, ProgramParam = 64,
    /// ProgramRecipe = 65, ProgramRecipeParam = 66, Catalog = 67, CatRef = 68, AGS = 69,
    /// AGSQueue = 70, Room = 71, Barcodes = 72, MacLEq = 73, LoadEquip = 74,
    /// Notify = 75, RoomCustomer = 76, ItemSpc = 77, ItemUOM = 78, MachineLog = 79,
    /// ProcessLog = 80, SplitTag = 81, SealerProgram = 82, SealerProcess = 83, PrinterLocation = 84,
    /// UserGroups = 85, UserGroupMembers = 86, ESignatureDefs = 87, ESignatures = 88, InputDefs_NOT_USED = 89,
    /// InputReply = 90, PrnRedirect = 91, StockGroup = 92, StockGroupRef = 93, FactoryItems = 94,
    /// FactoryPackings = 95, FactoryProducts = 96, FactoryUsers = 97, FactoryCustomers = 98, FactoryItemGrps = 99,
    /// FactoryItemSpcs = 100, FactorySuppliers = 101, RepSecurityGrp = 102, SPOSList = 103, ADGroups = 104,
    /// RepSecGrpMembers = 105, IESystems = 106, Job = 107, ChamberPlacements = 108, OrderInfo = 109,
    /// LotHc = 110, EndoDryingMethods = 111, FixedStockPlacements = 112, UnitWeightReg = 113, UnitWeightInfo = 114,
    /// WeightPlan = 115, WeightPlanEntries = 116, LocationGroup = 117, LocationGroupMembers = 118, FastTrackRules = 119,
    /// FastTrackRulesScope = 120, FastTrackRulesSelection = 121, FastTrackCode = 122, FastTrackPlan = 123, FastTrackPlanSteps = 124,
    /// FastTrackGroup = 125, FastTrackGroupCodes = 126, UnitFastTrack = 127, UnitFastTrackInvoice = 128, UnitFastTrackPlan = 129,
    /// WashCheck = 130, WashCheckType = 131, Desktop = 132, WeightValidationOverride = 133, PriceGroup = 134,
    /// CustomerUsers = 135, OrderTemplateType = 136, MachConsumables = 137, InfoOverviewConfig = 138, ProcessConsumables = 139,
    /// PreferenceListTemplates = 140, Indicator = 141, IndicatorType = 142, IndicatorTypeSteps = 143, IndicatorAction = 144,
    /// IndicatorMachineType = 145, IndicatorProduct = 146, IndicatorProgram = 147, IndicatorUnit = 148, ExtDocStore = 149,
    /// ExtDocRefLink = 150, ExtDocInfo = 151, MachConsType = 152, MachConsParam = 153, ProcParam = 154,
    /// MachRuleResult = 155, ProcBarcode = 156, McTypRule = 157, UnitTaT = 158, UnitTaTDef = 159,
    /// HandlingTypes = 160, HandlingStep = 161, TransportMethod = 162, UILayerDef = 163, UIGuideDef = 164,
    /// UISearchDef = 165, TextUser = 166, Transport = 167, HandlingResult = 168, Favorites = 169,
    /// ProcLoad = 170, PreferenceList = 171, PreferenceListLine = 172, PreferenceListLink = 173, OperationStaffLink = 174,
    /// CustSite = 175, PatientCat = 176, PrefListReplaceLine = 177, OrderAction = 178, OPDataAction = 179,
    /// DryerProcess = 180, WorkPeriods = 181, WorkHours = 182, Calendar = 183, Message = 184,
    /// MessageUserGroup = 185, MessageUserGroupLink = 186, MessageRecipientLink = 187, ProductTimes = 188, ActionLog = 189,
    /// ActionSubscriber = 190, Truck = 191, TruckStop = 192, Route = 193, RouteStop = 194,
    /// RouteTruck = 195, ProductReservation = 196, ItemReservation = 197, ALProcessApprove = 198, Question = 199,
    /// QuestionSet = 200, QuestionAnswer = 201, QuestionSetLink = 202, Action = 203, StockOrder = 204,
    /// ActionDelayLog = 205, MessageTemplates = 206, MessageTempPart = 207, MessageTempPartText = 208, MessageTempPartsLink = 209,
    /// MessageText = 210, ActionTemplates = 211, ImportHolidayLocation = 212, LotInfo = 213, OrderLotInfo = 214,
    /// UnitLotInfo = 215, PatientLotInfo = 216, IndicatorLotInfo = 217, Tags = 218, TagContentHistory = 219,
    /// TagContent = 220, TagLocation = 221, MessageGroupProfileLink = 222, MessageLabels = 223, MessageLabelLinks = 224,
    /// ExpTimePoints = 225, TableInfo = 226, Recent = 227, KPIValues = 228, CountingPoint = 229,
    /// CountingPointSet = 230, CountCountingSet = 231, OrderCountLst = 232, IntercomGroup = 233, IntercomGroupMembers = 234,
    /// MachDisplayGroupLink = 235, MachDisplayGroup = 236, CountChangeReason = 237, CountChanges = 238, FacCountChangeReason = 239,
    /// FacRepTyp = 240, CountDataUsers = 241, CountingPointData = 242, LinkStation = 243, ProcessLogQueue = 244,
    /// BioIndicatorType = 245, TimeRule = 246, TimeRuleGroup = 247, TimeRuleLink = 248, IncubatorLog = 249,
    /// IncubatorWellLog = 250, BITypePlacementLink = 251, FactoryTimeRuleGroup = 252, StandardComment = 253, FactoryStandardComment = 254,
    /// StandardCommentLink = 255, HandlingStepBinding = 256, IncubatorBatch = 257, CPUnitCheck = 258, FactoryAutoFTStocks = 259,
    /// DryerLog = 260, DryerPlacementLog = 261, PIPFields = 262, PIPAuditLog = 263, TagProgramGroupLink = 264,
    /// SpecLink = 265, EmgCaseCartType = 266, EmgCaseCartTypeLinks = 267, UserFieldDef = 268, CompAlternative = 269,
    /// IdenticalArticleGroup = 270, OrderLineAlternative = 271, OrderTempLineAlternative = 272, PrefListAlternative = 273, ClientTeam = 274,
    /// ServerPool = 275, ServerPoolClientTeams = 276, ServerPoolServers = 277, TagType = 278, MesOutTask = 279,
    /// MesTaskDef = 280, MesTaskLocations = 281, MesOutTaskTagList = 282, MesOutTaskEvent = 283, TegrisConfig = 284,
    /// PickJob = 285, PickJobContent = 286, PickJobAction = 287, PickJobOrderLink = 288, TriggerLink = 289,
    /// TriggerExclude = 290, SpotTest = 291, ItemExchange = 292, ScannerMacro = 293, GLNInfo = 294,
    /// MachLocation = 295, IOPosLink = 296, LoanerManProfile = 297, LoanerHandling = 298, NoMore = 299
    /// </para>
    /// </summary>
    public enum TDOCTable
    {
        None = 0,
        Text = 1,
        Pack = 2,
        PictureRef = 3,
        Program = 4,
        User = 5,
        MachineType = 6,
        Machine = 7,
        Cust = 8,
        Item = 9,
        Product = 10,
        System = 11,
        Composite = 12,
        Stock = 13,
        Process = 14,
        Unit = 15,
        Event = 16,
        Serial = 17,
        Trigger = 18,
        Supplier = 19,
        CustTransAct = 20,
        Pics = 21,
        BcTp = 22,
        Contact = 23,
        Profile = 24,
        ItemGrp = 25,
        Delta = 26,
        Position = 27,
        Patient = 28,
        PatientCons = 29,
        UnitLocation = 30,
        UnitList = 31,
        Repair = 32,
        RepairType = 33,
        Stocks = 34,
        Factory = 35,
        Location = 36,
        ProgGroups = 37,
        ProgGroup = 38,
        Report = 39,
        ReportDef = 40,
        RepSelection = 41,
        ItemSerialUsage = 42,
        Order = 43,
        OrderLine = 44,
        OrderLineSpec = 45,
        PosLocation = 46,
        PrnDrv = 47,
        Audit = 48,
        Defaults = 49,
        History = 50,
        TriggerLog = 51,
        OperationType = 52,
        ProcedureType = 53,
        ProcedureTypes = 54,
        ProcedureData = 55,
        OperationData = 56,
        Doctor = 57,
        OrderSuggestion = 58,
        OrderLineSugg = 59,
        OrderTemplate = 60,
        OrderLineTemp = 61,
        DefaultsBlob = 62,
        Batch = 63,
        ProgramParam = 64,
        ProgramRecipe = 65,
        ProgramRecipeParam = 66,
        Catalog = 67,
        CatRef = 68,
        AGS = 69,
        AGSQueue = 70,
        Room = 71,
        Barcodes = 72,
        MacLEq = 73,
        LoadEquip = 74,
        Notify = 75,
        RoomCustomer = 76,
        ItemSpc = 77,
        ItemUOM = 78,
        MachineLog = 79,
        ProcessLog = 80,
        SplitTag = 81,
        SealerProgram = 82,
        SealerProcess = 83,
        PrinterLocation = 84,
        UserGroups = 85,
        UserGroupMembers = 86,
        ESignatureDefs = 87,
        ESignatures = 88,
        InputDefs_NOT_USED = 89,
        InputReply = 90,
        PrnRedirect = 91,
        StockGroup = 92,
        StockGroupRef = 93,
        FactoryItems = 94,
        FactoryPackings = 95,
        FactoryProducts = 96,
        FactoryUsers = 97,
        FactoryCustomers = 98,
        FactoryItemGrps = 99,
        FactoryItemSpcs = 100,
        FactorySuppliers = 101,
        RepSecurityGrp = 102,
        SPOSList = 103,
        ADGroups = 104,
        RepSecGrpMembers = 105,
        IESystems = 106,
        Job = 107,
        ChamberPlacements = 108,
        OrderInfo = 109,
        LotHc = 110,
        EndoDryingMethods = 111,
        FixedStockPlacements = 112,
        UnitWeightReg = 113,
        UnitWeightInfo = 114,
        WeightPlan = 115,
        WeightPlanEntries = 116,
        LocationGroup = 117,
        LocationGroupMembers = 118,
        FastTrackRules = 119,
        FastTrackRulesScope = 120,
        FastTrackRulesSelection = 121,
        FastTrackCode = 122,
        FastTrackPlan = 123,
        FastTrackPlanSteps = 124,
        FastTrackGroup = 125,
        FastTrackGroupCodes = 126,
        UnitFastTrack = 127,
        UnitFastTrackInvoice = 128,
        UnitFastTrackPlan = 129,
        WashCheck = 130,
        WashCheckType = 131,
        Desktop = 132,
        WeightValidationOverride = 133,
        PriceGroup = 134,
        CustomerUsers = 135,
        OrderTemplateType = 136,
        MachConsumables = 137,
        InfoOverviewConfig = 138,
        ProcessConsumables = 139,
        PreferenceListTemplates = 140,
        Indicator = 141,
        IndicatorType = 142,
        IndicatorTypeSteps = 143,
        IndicatorAction = 144,
        IndicatorMachineType = 145,
        IndicatorProduct = 146,
        IndicatorProgram = 147,
        IndicatorUnit = 148,
        ExtDocStore = 149,
        ExtDocRefLink = 150,
        ExtDocInfo = 151,
        MachConsType = 152,
        MachConsParam = 153,
        ProcParam = 154,
        MachRuleResult = 155,
        ProcBarcode = 156,
        McTypRule = 157,
        UnitTaT = 158,
        UnitTaTDef = 159,
        HandlingTypes = 160,
        HandlingStep = 161,
        TransportMethod = 162,
        UILayerDef = 163,
        UIGuideDef = 164,
        UISearchDef = 165,
        TextUser = 166,
        Transport = 167,
        HandlingResult = 168,
        Favorites = 169,
        ProcLoad = 170,
        PreferenceList = 171,
        PreferenceListLine = 172,
        PreferenceListLink = 173,
        OperationStaffLink = 174,
        CustSite = 175,
        PatientCat = 176,
        PrefListReplaceLine = 177,
        OrderAction = 178,
        OPDataAction = 179,
        DryerProcess = 180,
        WorkPeriods = 181,
        WorkHours = 182,
        Calendar = 183,
        Message = 184,
        MessageUserGroup = 185,
        MessageUserGroupLink = 186,
        MessageRecipientLink = 187,
        ProductTimes = 188,
        ActionLog = 189,
        ActionSubscriber = 190,
        Truck = 191,
        TruckStop = 192,
        Route = 193,
        RouteStop = 194,
        RouteTruck = 195,
        ProductReservation = 196,
        ItemReservation = 197,
        ALProcessApprove = 198,
        Question = 199,
        QuestionSet = 200,
        QuestionAnswer = 201,
        QuestionSetLink = 202,
        Action = 203,
        StockOrder = 204,
        ActionDelayLog = 205,
        MessageTemplates = 206,
        MessageTempPart = 207,
        MessageTempPartText = 208,
        MessageTempPartsLink = 209,
        MessageText = 210,
        ActionTemplates = 211,
        ImportHolidayLocation = 212,
        LotInfo = 213,
        OrderLotInfo = 214,
        UnitLotInfo = 215,
        PatientLotInfo = 216,
        IndicatorLotInfo = 217,
        Tags = 218,
        TagContentHistory = 219,
        TagContent = 220,
        TagLocation = 221,
        MessageGroupProfileLink = 222,
        MessageLabels = 223,
        MessageLabelLinks = 224,
        ExpTimePoints = 225,
        TableInfo = 226,
        Recent = 227,
        KPIValues = 228,
        CountingPoint = 229,
        CountingPointSet = 230,
        CountCountingSet = 231,
        OrderCountLst = 232,
        IntercomGroup = 233,
        IntercomGroupMembers = 234,
        MachDisplayGroupLink = 235,
        MachDisplayGroup = 236,
        CountChangeReason = 237,
        CountChanges = 238,
        FacCountChangeReason = 239,
        FacRepTyp = 240,
        CountDataUsers = 241,
        CountingPointData = 242,
        LinkStation = 243,
        ProcessLogQueue = 244,
        BioIndicatorType = 245,
        TimeRule = 246,
        TimeRuleGroup = 247,
        TimeRuleLink = 248,
        IncubatorLog = 249,
        IncubatorWellLog = 250,
        BITypePlacementLink = 251,
        FactoryTimeRuleGroup = 252,
        StandardComment = 253,
        FactoryStandardComment = 254,
        StandardCommentLink = 255,
        HandlingStepBinding = 256,
        IncubatorBatch = 257,
        CPUnitCheck = 258,
        FactoryAutoFTStocks = 259,
        DryerLog = 260,
        DryerPlacementLog = 261,
        PIPFields = 262,
        PIPAuditLog = 263,
        TagProgramGroupLink = 264,
        SpecLink = 265,
        EmgCaseCartType = 266,
        EmgCaseCartTypeLinks = 267,
        UserFieldDef = 268,
        CompAlternative = 269,
        IdenticalArticleGroup = 270,
        OrderLineAlternative = 271,
        OrderTempLineAlternative = 272,
        PrefListAlternative = 273,
        ClientTeam = 274,
        ServerPool = 275,
        ServerPoolClientTeams = 276,
        ServerPoolServers = 277,
        TagType = 278,
        MesOutTask = 279,
        MesTaskDef = 280,
        MesTaskLocations = 281,
        MesOutTaskTagList = 282,
        MesOutTaskEvent = 283,
        TegrisConfig = 284,
        PickJob = 285,
        PickJobContent = 286,
        PickJobAction = 287,
        PickJobOrderLink = 288,
        TriggerLink = 289,
        TriggerExclude = 290,
        SpotTest = 291,
        ItemExchange = 292,
        ScannerMacro = 293,
        GLNInfo = 294,
        MachLocation = 295,
        IOPosLink = 296,
        LoanerManProfile = 297,
        LoanerHandling = 298,
        NoMore = 299
    }; // TDOCTable

    /// <summary>
    /// Values:
    /// <para>
    /// Admin = 0, Scanner = 1, Machine = 2
    /// </para>
    /// </summary>
    public enum ThingType
    {
        Admin = 0,
        Scanner = 1,
        Machine = 2
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Default = 0, Visible = 1, Advanced = 2, Hidden = 3
    /// </para>
    /// </summary>
    public enum UILocaAvailability
    {
        Default = 0,
        Visible = 1,
        Advanced = 2,
        Hidden = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// OwnOnly = 0, OwnSiteOnly = 1, All = 2, OwnSiteOrCust = 3
    /// </para>
    /// </summary>
    public enum WebDisplayCustomerProductsMode
    {
        OwnOnly = 0,
        OwnSiteOnly = 1,
        All = 2,
        OwnSiteOrCust = 3
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Allowed = 0, Blocked = 1
    /// </para>
    /// </summary>
    public enum WebDisplayGeneralProductsMode
    {
        Allowed = 0,
        Blocked = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// ShowAll = 0, HideAll = 1
    /// </para>
    /// </summary>
    public enum WebDisplayPriceMode
    {
        ShowAll = 0,
        HideAll = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// AllowEdit = 0, NotAllowEdit = 1
    /// </para>
    /// </summary>
    public enum WebEditOprationArticlesMode
    {
        AllowEdit = 0,
        NotAllowEdit = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// On = 0, Off = 1
    /// </para>
    /// </summary>
    public enum WebFastTrackMode
    {
        On = 0,
        Off = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// On = 0, Off = 1
    /// </para>
    /// </summary>
    public enum WebOrderMode
    {
        On = 0,
        Off = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Allow = 0, NotAllow = 1
    /// </para>
    /// </summary>
    public enum WebStartStopOperationMode
    {
        Allow = 0,
        NotAllow = 1
    };

    /// <summary>
    /// Values:
    /// <para>
    /// Nothing = 0, Pack = 1, SteriPostBatch = 2, Out = 3, Return = 4,
    /// Prepare = 5, Wrap = 6, LitePro = 7, SteriPreBatch = 8, Flash = 9,
    /// Location = 10, WashPreBatch = 11, WashPostBatch = 12, Opened = 13, Operation = 14,
    /// Order = 15, Cancel = 16, Industry = 17, ReturnToFactory = 18, OrderPick = 19,
    /// OutDock = 20, PreDisinfect = 21, ReturnOrderPick = 22, SentToRepair = 23, ReceivedFromRepair = 24,
    /// CancelledRepair = 25, InitUnitCreated = 26, DispUnitCreated = 27, PackStart = 28, PrepareStart = 29,
    /// Transport = 30, EndoClean = 31, ManualEndoDryingStart = 32, ManualEndoDryingStop = 33, OrderUnPick = 34,
    /// OperationPreCount = 35, OperationPerCount = 36, OperationPostCount = 37, ManualEndoDryingAssumed = 38, SecondApproval = 39,
    /// SkippedSecondApproval = 40, Last = 41
    /// </para>
    /// </summary>
    public enum WhatType
    {
        Nothing = 0,
        Pack = 1,
        SteriPostBatch = 2,
        Out = 3,
        Return = 4,
        Prepare = 5,
        Wrap = 6,
        LitePro = 7,
        SteriPreBatch = 8,
        Flash = 9,
        Location = 10,
        WashPreBatch = 11,
        WashPostBatch = 12,
        Opened = 13,
        Operation = 14,
        Order = 15,
        Cancel = 16,
        Industry = 17,
        ReturnToFactory = 18,
        OrderPick = 19,
        OutDock = 20,
        PreDisinfect = 21,
        ReturnOrderPick = 22,
        SentToRepair = 23,
        ReceivedFromRepair = 24,
        CancelledRepair = 25,
        InitUnitCreated = 26,
        DispUnitCreated = 27,
        PackStart = 28,
        PrepareStart = 29,
        Transport = 30,
        EndoClean = 31,
        ManualEndoDryingStart = 32,
        ManualEndoDryingStop = 33,
        OrderUnPick = 34,
        OperationPreCount = 35,
        OperationPerCount = 36,
        OperationPostCount = 37,
        ManualEndoDryingAssumed = 38,
        SecondApproval = 39,
        SkippedSecondApproval = 40,
        Last = 41
    }; // WhatType

    /// <summary>
    /// Values:
    /// <para>
    /// PrimarySteri = 0, FlashSteri = 10, PreDisinfect = 50, PreWash = 100,
    /// ExtraWash = 110, PostWash = 190
    /// </para>
    /// </summary>
    public enum BatchType
    {
        PrimarySteri = 0,
        FlashSteri = 10,
        PreDisinfect = 50,
        PreWash = 100,
        ExtraWash = 110,
        PostWash = 190
    };
}

#pragma warning restore 1591